### PR TITLE
Train on existing weights

### PR DESCRIPTION
**Pull request by ajay-bhargava**
This pull request adds code to YOLOv5 that will allow .tar.gz or .pt files to be downloaded from S3 and loaded into YOLOv5 for transfer-learning/fine-tuning existing by specifying it in the `--weights` flag at execution time.

### CODE REVIEW

**Comment by ajay-bhargava** [comment]
Hey @ml1976 @ZackSchmidt1 I need help. I have modified the check suffix function and tested it out as such: 

```python
def check_suffix(file='yolov5s.pt', suffix=('.pt', '.gz'), msg=''):
    # Check file(s) for acceptable suffixes
    if file and suffix:
        print('This is the file used in the program {}'.format(file))
        if isinstance(suffix, str):
            suffix = [suffix]
        for f in file if isinstance(file, (list, tuple)) else [file]:
            s = Path(f).suffix.lower()  # file suffix
            print('Here are the Suffix of the file: {}'.format(s)) # Adding Debugging
            if len(s):
                assert s in suffix, f"{msg}{f} acceptable suffix is {suffix}"
```
supplying a URL like this:
`uri = 's3://sagemaker-us-west-2-388576304176/30-07-2022-21-01-08-People-Vehicle-YOLOv5-Estimator/output/model.tar.gz'`

Yields no error, however when I run YOLOv5 with this modification I still get the assertion error. What do you think i'm missing?

**Review by ZackSchmidt1 — APPROVED** [review]
I'm guessing the line added in train.py worked as a fix? Awesome, this was very enlightening for me

**Review by ml1976 — APPROVED** [review]

**Comment by ajay-bhargava** [comment]
Guys, please see final review and review the wiki page to understand how pre-trained weights is done: 
https://github.com/aegissystems/ds-sagemaker-yolov5/wiki/Pre-trained-weights

**Comment by ZackSchmidt1** [comment]
I see in the wiki that it requires .pt as the extension, but in the code it looks like a .tar.gz works as well?

**Comment by ZackSchmidt1** [comment]
Oops, I see, the weights have that .pt requirement, then the weights are required to be tarballed and zipped. Got it!

**Pull request merged**
